const CONSTANTS = {
  AUTH: {
    LOGIN: '@@AUTH/LOGIN',
    LOGIN_SUCCESS: '@@AUTH/LOGIN/SUCCESS',
    LOGIN_FAILURE: '@@AUTH/LOGIN/FAILURE',
    LOGOUT: '@@AUTH/LOGOUt'
  },
  USER: {
    CREATE: '@@USER/CREATE',
    CREATE_SUCCESS: '@@USER/CREATE/SUCCESS',
    CREATE_FAILURE: '@@USER/CREATE/FAILURE',
    DELETE: '@@USER/DELETE',
    DELETE_SUCCESS: '@@USER/DELETE/SUCCESS',
    DELETE_FAILURE: '@@USER/DELETE/FAILURE',
  }
}

export default CONSTANTS;